steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/microservice2:latest', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/microservice2:latest']
- name: 'gcr.io/cloud-builders/kubectl'
  args:
  - 'set'
  - 'image'
  - 'deployment/microservice2'
  - 'microservice2=gcr.io/$PROJECT_ID/microservice2:latest'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=northamerica-northeast1'
  - 'CLOUDSDK_CONTAINER_CLUSTER=autopilot-cluster-1'
images:
- 'gcr.io/$PROJECT_ID/microservice2:latest'
options:
  logging: CLOUD_LOGGING_ONLY
timeout: '1200s'
