steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/microservice2:$COMMIT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/microservice2:$COMMIT_SHA']
- name: 'gcr.io/cloud-builders/kubectl'
  args:
  - 'set'
  - 'image'
  - 'deployment/microservice2'
  - 'microservice2=gcr.io/$PROJECT_ID/microservice2:$COMMIT_SHA'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1'
  - 'CLOUDSDK_CONTAINER_CLUSTER=my-gke-cluster'
- name: 'gcr.io/cloud-builders/kubectl'
  args:
  - 'rollout'
  - 'restart'
  - 'deployment/microservice2'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1'
  - 'CLOUDSDK_CONTAINER_CLUSTER=my-gke-cluster'
images:
- 'gcr.io/$PROJECT_ID/microservice2:$COMMIT_SHA'
options:
  logging: CLOUD_LOGGING_ONLY
timeout: '1200s'
